### ISSUE TITLE
Upload to AppstoreConnect is failing. Bundle is invalid with the latest AirshipBindings (iOS)

### ISSUE THREAD

**Issue by ohazar** [urbanairship/urbanairship-xamarin#182] opened 2021-07-09 11:42 UTC
Hello,

We are using the latest version of your nuget package (12.0). We get the following error when we try to upload our app to AppstoreConnect.

Here are the packages we are using;
![ss](https://user-images.githubusercontent.com/27765465/125072646-7e787480-e0c3-11eb-93d0-17805edd7de9.png)
![ss2](https://user-images.githubusercontent.com/27765465/125072792-b2ec3080-e0c3-11eb-9c17-0d5ef62635bb.png)

From Apple's Email;

_We identified one or more issues with a recent delivery for your app. Please correct the following issues, then upload again._

```
ITMS-90036: This bundle is invalid - The Info.plist file for /Payload/DDPYogaiOS.app/AirshipBindings.iOS.Core.resources/AirshipCore.xcframework/ios-arm64/AirshipCore.framework is missing or could not be read.

ITMS-90207: Invalid Bundle - The bundle at '/Payload/DDPYogaiOS.app/AirshipBindings.iOS.Core.resources/AirshipCore.xcframework/ios-arm64/AirshipCore.framework' does not contain a bundle executable.

ITMS-90036: This bundle is invalid - The Info.plist file for /Payload/DDPYogaiOS.app/AirshipBindings.iOS.Core.resources/AirshipCore.xcframework/ios-arm64_x86_64-maccatalyst/AirshipCore.framework is missing or could not be read.

ITMS-90207: Invalid Bundle - The bundle at '/Payload/DDPYogaiOS.app/AirshipBindings.iOS.Core.resources/AirshipCore.xcframework/ios-arm64_x86_64-maccatalyst/AirshipCore.framework' does not contain a bundle executable.

ITMS-90036: This bundle is invalid - The Info.plist file for /Payload/DDPYogaiOS.app/AirshipBindings.iOS.Core.resources/AirshipCore.xcframework/ios-arm64_x86_64-simulator/AirshipCore.framework is missing or could not be read.

ITMS-90207: Invalid Bundle - The bundle at '/Payload/DDPYogaiOS.app/AirshipBindings.iOS.Core.resources/AirshipCore.xcframework/ios-arm64_x86_64-simulator/AirshipCore.framework' does not contain a bundle executable.

ITMS-90036: This bundle is invalid - The Info.plist file for /Payload/DDPYogaiOS.app/AirshipBindings.iOS.Core.resources/AirshipCore.xcframework/tvos-arm64/AirshipCore.framework is missing or could not be read.

ITMS-90207: Invalid Bundle - The bundle at '/Payload/DDPYogaiOS.app/AirshipBindings.iOS.Core.resources/AirshipCore.xcframework/tvos-arm64/AirshipCore.framework' does not contain a bundle executable.

ITMS-90036: This bundle is invalid - The Info.plist file for /Payload/DDPYogaiOS.app/AirshipBindings.iOS.Core.resources/AirshipCore.xcframework/tvos-arm64_x86_64-simulator/AirshipCore.framework is missing or could not be read.

ITMS-90207: Invalid Bundle - The bundle at '/Payload/DDPYogaiOS.app/AirshipBindings.iOS.Core.resources/AirshipCore.xcframework/tvos-arm64_x86_64-simulator/AirshipCore.framework' does not contain a bundle executable.

ITMS-90036: This bundle is invalid - The Info.plist file for /Payload/DDPYogaiOS.app/AirshipBindings.iOS.MessageCenter.resources/AirshipMessageCenter.xcframework/ios-arm64/AirshipMessageCenter.framework is missing or could not be read.

ITMS-90207: Invalid Bundle - The bundle at '/Payload/DDPYogaiOS.app/AirshipBindings.iOS.MessageCenter.resources/AirshipMessageCenter.xcframework/ios-arm64/AirshipMessageCenter.framework' does not contain a bundle executable.

ITMS-90036: This bundle is invalid - The Info.plist file for /Payload/DDPYogaiOS.app/AirshipBindings.iOS.MessageCenter.resources/AirshipMessageCenter.xcframework/ios-arm64_x86_64-maccatalyst/AirshipMessageCenter.framework is missing or could not be read.

ITMS-90207: Invalid Bundle - The bundle at '/Payload/DDPYogaiOS.app/AirshipBindings.iOS.MessageCenter.resources/AirshipMessageCenter.xcframework/ios-arm64_x86_64-maccatalyst/AirshipMessageCenter.framework' does not contain a bundle executable.

ITMS-90036: This bundle is invalid - The Info.plist file for /Payload/DDPYogaiOS.app/AirshipBindings.iOS.MessageCenter.resources/AirshipMessageCenter.xcframework/ios-arm64_x86_64-simulator/AirshipMessageCenter.framework is missing or could not be read.

ITMS-90207: Invalid Bundle - The bundle at '/Payload/DDPYogaiOS.app/AirshipBindings.iOS.MessageCenter.resources/AirshipMessageCenter.xcframework/ios-arm64_x86_64-simulator/AirshipMessageCenter.framework' does not contain a bundle executable.
```

**Comment by marc-scig** [comment] 2021-07-09 18:16
Hi @ohazar,

Thanks for the report, and I'm sorry you're having difficulty submitting your app. This is looks like it's related to some workarounds we had to do in the bindings to support using xcframeworks in version 12.0. I'm not sure what the problem is yet, but we're looking into it.

**Comment by marc-scig** [comment] 2021-07-13 01:18
@ohazar can you share some details about your dev environment? OS, Visual Studio version, etc?

The logs in the Apple email look a bit strange to me. When I archive a test app containing the urbanairship.ios.core package (using the "archive for publishing" command in Visual Studio), I don't see any AirshipBindings.iOS.*.resources style directories in the archived app bundle at all. I do see AirshipCore.framework, under the directory "Frameworks". The resources directories are a workaround along with a few .targets and nuspec hacks to make it possible for VS to consume the appropriate framework for the selected architecture at build time. But as far as I know they shouldn't end up in the archive.

**Comment by ohazar** [comment] 2021-07-28 11:44
We removed those 4 resources folders from project directory manually and solved the submitting issue. After re-updating the packages, we don't get these resources folders again. It could be a nuget update issue or you may look at how your nuget packaging is created. Thank you for help.

**Comment by marc-scig** [comment] 2021-07-29 18:07
Thanks @ohazar. I'm going to close this for now.

**Closed by marc-scig** 2021-07-29 18:07 UTC
